services:
  - type: web
    name: sea-lion-app
    env: python
    plan: free
    rootDir: .
    buildCommand: |
      set -e
      echo "==> Building frontend"
      cd frontend
      npm ci || npm install
      npm run build
      ls -la dist || true

      echo "==> Installing backend deps"
      cd ..
      pip install --upgrade pip setuptools wheel
      pip install -r backend/requirements.txt

      echo "==> Copying frontend build into backend/frontend_dist"
      rm -rf backend/frontend_dist
      mkdir -p backend/frontend_dist
      cp -r frontend/dist/* backend/frontend_dist/
      ls -la backend/frontend_dist || true

    # IMPORTANT: module path + app-dir must match your layout
    startCommand: uvicorn app.main:app --app-dir backend --host 0.0.0.0 --port $PORT

    envVars:
      - key: SEA_LION_API_KEY
        sync: false
      - key: HUGGINGFACE_API_TOKEN
        sync: false
      - key: CHROMA_DB_DIR
        value: /data/chroma_lessons
      - key: SEA_LION_BASE_URL
        value: https://api.sea-lion.ai/v1/chat/completions
      - key: DEFAULT_SEALION_MODEL
        value: aisingapore/Gemma-SEA-LION-v3-9B-IT
      - key: HF_EMBED_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: HF_EMBED_API
        value: https://router.huggingface.co/hf-inference/models/sentence-transformers/all-MiniLM-L6-v2/pipeline/feature-extraction

    disk:
      name: chroma-disk
      mountPath: /data
      sizeGB: 1

    